### ISSUE TITLE
Socratic Seminar #22 Topics

### ISSUE THREAD

**Issue by glozow** [londonbitdevs/londonbitdevs-website#9]
Gathering topics to discuss.
Categories:
-    News
-    New Work/Research, ML posts
-    Bitcoin Projects
-    Lightning Projects
-    Client Software Projects

**Comment by glozow** [comment]
https://github.com/BitDevsNYC/BitDevsNYC.github.io/pull/124

**Comment by ConorOkus** [comment]
**News**

- Voltage releases new [LSP](https://voltage.cloud/blog/voltage-announcements/introducing-flow-v2/) on testnet
- The top wallets used to make [bitcoin lightning payments](https://twitter.com/BitPay/status/1628077236443131909)
- Mastering Bitcoin v3 [early release](https://twitter.com/hrdng/status/1628862270607605761)

**Comment by ConorOkus** [comment]
**Research**

- Doing a simulation for upfront [probing success rates](https://lists.linuxfoundation.org/pipermail/lightning-dev/2023-February/003853.html)

**Comment by ConorOkus** [comment]
**Bitcoin Projects**

- [BDK 1.0 Incoming](https://github.com/LLFourn/bdk_core_staging), [the road to BDK 1.0](https://bitcoindevkit.org/blog/road-to-bdk-1/)

**Comment by ConorOkus** [comment]
Lightning Projects

- [LDK Node](https://github.com/lightningdevkit/ldk-node)

**Comment by stickies-v** [comment]
**Bitcoin Projects**
- Liana: [0.2: now with multisig!](https://github.com/wizardsardine/liana/releases/tag/0.2) (+ general discussion about degrading timelocks and how taproot partially improves that but still requires periodically respending UTXOs without some kind of covenant)
- [Ordinals](https://docs.ordinals.com/) and [Inscriptions](https://docs.ordinals.com/inscriptions.html) (and now also https://openordex.org/ with PSBTs)
- [OP_CTV](https://github.com/bitcoin-inquisition/bitcoin/pull/17) and [SIGHASH_ANYPREVOUT](https://github.com/bitcoin-inquisition/bitcoin/pull/18) merged in bitcoin-inquisition
- Bitcoin Core: [p2p, validation: Don't download witnesses for assumed-valid blocks when running in prune mode](https://github.com/bitcoin-inquisition/bitcoin/pull/18) merged
- Bitcoin Core: [Signing support for Miniscript Descriptors](https://github.com/bitcoin/bitcoin/pull/24149) merged

**Research**
- [Fedipool: Fedimint Could Mitigate Bitcoin Mining Pool Concerns](https://www.discreetlog.com/fedipool/) (not sure if really "research" but probably more so than news?)

**New Work**
- [BitcoinSearch.xyz](https://bitcoinsearch.xyz/) is a recently-launched search engine for Bitcoin technical documentation and discussions.
